### ISSUE TITLE
Change to ratios in calculator?

### ISSUE THREAD

**Issue by willcrick** [hendricius/pizza-dough#101]
Maybe a question rather than an issue, but this week I went to use the trusty calculator for 10 pizza @280 grams, and the amount of sourdough starter it recommended was 67 grams. A few weeks ago, I did 10 pizzas @250g and it said 309g. I know the total is slightly different, but the difference in starter is enormous! Is this a new improved recipe? I am going to stick with the previous amount as it worked and I am entertaining tomorrow and don't fancy a pizza flop 😬.
But if you say this is correct I will give it a go next time, as youre the pizza man.

**Comment by hendricius** [comment]
Thanks! Yep :-). That is correct. I adjusted the recipe a bit. I am now always using a stiff sourdough starter to make the dough. It has the same hydration as the actual dough. It really makes things a lot easier.

**Comment by willcrick** [comment]
Ok, good to know. The recipe has changed too, will do a full run through next time. Thanks for all your words of dough wisdom 👌
