### ISSUE TITLE
Does not run out of the box

### ISSUE THREAD

**Issue by jhaungs** [hendricius/pizza-dough#103]
The Gemfile line: 

```gem "sassc-rails"```

is commented out, so you have to manually install sassc. Then when you do, you need to run:

```rake assets:precompile```

to get the initial page to load.

**Comment by hendricius** [comment]
Thanks! Could you check if it works please? I update the installation instructions. I am using the dart sass gem, that's why `sassc` is no longer needed.

**Comment by hendricius** [comment]
In #106 I have also added a docker option. You could just start everything with `make up` now provided you have docker installed.
