### ISSUE TITLE
Salt not in Dough Ingredients 

### ISSUE THREAD

**Issue by hunterhayes** [hendricius/pizza-dough#110]
Hi, really love the pizza calculator, but wanted to point out a bug. When you select sourdough as your dough type, salt does not show up in the ingredients in the calculator. The math is correct for the other ingredients, it's just missing the salt output. One can easily do the math to find the missing amount, but that seems to obviate the need for a web calculator 😬

Thanks!

**Comment by hendricius** [comment]
Thanks for the report! I finally managed to fix it 😎
