### ISSUE TITLE
Pizza dough calculator

### ISSUE THREAD

**Issue by butterfly-pn** [hendricius/pizza-dough#21]
Hey,
I am learning frontend development and in my opinion the best way to learn something is to try it 😉. So what do you think if I do a redesign of your calculator? I already have an idea and you can see it here: https://www.figma.com/proto/fS1VRECfnZGE6TOg89goMmh2/Pizza-Dough-Calculator?node-id=2%3A0&viewport=695%2C443%2C0.73733&scaling=scale-down

**Comment by hendricius** [comment]
Haha, amazing. That looks pretty cool. I made a small video with some feedback. Hope it helps: https://app.hyfy.io/share/abZLowbOCmn/

**Comment by butterfly-pn** [comment]
Here's demo preview 😉 
https://butterfly-pn.github.io/pizza-dough/

**Comment by sm4rk0** [comment]
I've noticed a typo and created a pull request (for both repos).

**Comment by hendricius** [comment]
Good job. I love it.

I just had a few small suggestions for alignment on the final page where results are shown.

![image](https://user-images.githubusercontent.com/816859/51730588-55410680-2078-11e9-9ad9-a55d3fe38462.png)

**Comment by sm4rk0** [comment]
I suggest adding a step="50" to weight input and maybe a default value of 200.

**Comment by butterfly-pn** [comment]
In my opinion, 50 is too big for step. The default value is a good idea 👍

**Comment by sm4rk0** [comment]
OK, then it can be smaller, but 1g makes no sense.
And also, default value for number of pizzas could be useful (1?).

**Comment by hendricius** [comment]
5 sounds like a good step size. How about 2 pizzas by default?
