### ISSUE TITLE
Dough tearing in the middle

### ISSUE THREAD

**Issue by c-kirkeby** [hendricius/pizza-dough#27]
Really enjoying this guide and have been following your sourdough guide. I have been making 1:30 hour pizza doughs in the past and the extra flavour and crispiness this recipe brought out was really fantastic.

At the 24 hour mark during step three, I found that the middle was getting too thin within only a few seconds so I ended up having to gently stretch it out on the work surface, but even then I got some tears that I had to pinch to fix.

Could this be from a lack of kneading? I did the folds described at the start but perhaps I didn't pull it up high enough.

**Comment by hendricius** [comment]
Sorry - I must have overseen this.

Try reducing the amount of bench rest that you have for your dough. While your dough rests, gluten will relax. That way it does not stick together well enough. It could also simply be the flour that you are using. How much protein does it have? The more protein, the merrier.
