### ISSUE TITLE
Unit for the calculator's water quantity

### ISSUE THREAD

**Issue by tuomashatakka** [hendricius/pizza-dough#28]
Hello

I think that milliliters would be preferable units for the water quantity display. It's a bit unconventional to display the water quantity as grams - thus it would be more practical to show them as ml.

I could do a pull request for this if this sounds reasonable :-)

**Comment by hendricius** [comment]
Me personally I rather have the grams. That way it matches with the scale :).

**Comment by B-Galati** [comment]
Agree with @hendricius even if at the end it's all the same thing.
