### ISSUE TITLE
Yeast percentage correct?

### ISSUE THREAD

**Issue by Roonerelli** [hendricius/pizza-dough#29]
I followed your recipe for 4 pies : 

Flour 100.00% 478.90 g
Water 65.00% 311.28 g
Salt 2.00% 9.58g
Yeast 0.05% 0.24g

I followed the amounts above and the dough didn't rise or form into a ball
I used brand new Saf-Levure yeast (not expired) and Caputo 00 flour Maldon salt and bottled water. and followed the timings in your guide

Are you sure the yeast percentage is correct? Most recipes I've since searched for recommend about 10 times that 

Thanks!

**Comment by hendricius** [comment]
Yes. It's correct. Yeast will reproduce. Good things come to those who wait haha. If you have less time, you can also use more yeast. In my case, when using more with the overnight technique, the dough just collapses in the morning as it inflated too much.

**Comment by Roonerelli** [comment]
hey - thanks for the reply. will give it another try

cheers

**Comment by Roonerelli** [comment]
Hi again - just trying this again tonight. 4 pizzas require 0.24g of yeast. I have measured that on a scale with 0.01 accuracy, and it is a tiny, tiny amount. Like the tip of a teaspoon. does that sound about right for 4 pizzas? @hendricius 

thanks!

**Comment by hendricius** [comment]
Yes. That's correct. It's a really tiny amount of yeast.

It's at room temperature over night. 

How did it turn out?

**Comment by Roonerelli** [comment]
hey - much better this time!
I didn't shape the dough back into balls when I took it out of the fridge though (when waiting for it to come up to room temperature before shaping). And so it started expanding a little bit. So I need to make sure I do that next time. 
And I still need to get better at the shaping too (but I gather that's generally the difficult bit anyway)
But definitely moving in the right direction.
Tasted great though, which I guess is the main thing
thanks for the reply
cheers,
