### ISSUE TITLE
How about using pizza Semolina?

### ISSUE THREAD

**Issue by jyavenard** [hendricius/pizza-dough#33]
Lots of Italian stores actually sell "Semola di grano duro" for pizza?

They are typically very high in protein (over 14%). Can this be substituted for flour easily?

**Comment by jyavenard** [comment]
Well, I did use 800g of it over the week end. The results were terrific.
I did have to add half a cup of water whenever I did the stretch&fold as it was still very dry.

Flavour was definitely there.

**Comment by hendricius** [comment]
@jyavenard - sorry for the late response. Yes. You can use all sorts of flour that has gluten. It's just not the original neapolitan pizza. But I am sure it will taste great regardless.

**Comment by hendricius** [comment]
Feel free to re-open the issue again if needed :)
