### ISSUE TITLE
Problems w/ video link

### ISSUE THREAD

**Issue by mnissov** [hendricius/pizza-dough#52]
The link to ["watch the whole process as a video"](https://camo.githubusercontent.com/35038173c8f4f2cbb989f4f1b9945ad2e7e0c628/68747470733a2f2f7777772e796f75747562652e636f6d2f77617463683f763d7568664f5f67724a457551) isn't working for me. It returns a white screen which says "Non-Image content-type returned".

Is that an error on my end or yours?

**Comment by szepeviktor** [comment]
Please get #44 merged.

**Comment by hendricius** [comment]
Thank you. Merged it.
