### ISSUE TITLE
Major rework of the recipe

### ISSUE THREAD

**Issue by hendricius** [hendricius/pizza-dough#54]
I have been busy experimenting with pizza and found a few good ideas to simplify/enhance the recipe.

![image](https://user-images.githubusercontent.com/816859/71666735-8931ab00-2d62-11ea-8960-60b1c47f354f.png)

1. I will change the shaping of the dough balls part.
2. I am going to remove the olive oil part. 
3. Instead I suggest to cover each of the dough balls with a small bowl.
4. This simplifies the final step, where you can then just take the dough ball without much work and shape it into your desired pizza.

Not sure when I have the time, but just a quick heads up. Happy baking everyone.

**Comment by NelTdS** [comment]
Have you tried making a dough with 70% hydration? Of course, it depends on one's individual taste, but after testing different hydration levels, I much prefer the structure of a 70% hydration dough. However, handling becomes a bit more difficult, as the dough gets softer and stickier.

**Comment by hendricius** [comment]
Fixed in https://github.com/hendricius/pizza-dough/pull/97
