### ISSUE TITLE
Water percentage

### ISSUE THREAD

**Issue by mischw** [hendricius/pizza-dough#57]
Any particular reason why you reduced the default water percentage from 65% to 60%?

Also the german translation of the ReadMe still reflects the old value of 65% water.

**Comment by vpilkevych** [comment]
Would you accept a PR to make the hydration a parameter?

**Comment by hendricius** [comment]
Thanks! It is fixed in https://github.com/hendricius/pizza-dough/pull/85. I deleted the German version, it's too much work to maintain it.
