### ISSUE TITLE
This dough does not rise with so little yeast

### ISSUE THREAD

**Issue by vladola** [hendricius/pizza-dough#60]
I followed the recipe to the letter, same ingredients. It surprised me a lot when I noticed there was so little yeast my scale would not even register it but I went along with it.

Unless tomorrow miraculously the dough rises (which I doubt), there is far too little yeast in the original recipe... not sure why would you recommend such a low amount.

I'll update tomorrow.

**Comment by vladola** [comment]
So the daw maybe grew 10% or so in 24 hours... not impressed. 
I'LL see what kind of pizza comes out of it but am not hopefull....

Like other issues have said, more yeast is necessary. Will report back once i make the pizza.

**Comment by vladola** [comment]
So, I made the pizza last night. Here's my thoughts:

Surprisingly the dough did grow inside the oven like normal pizza. The difference in taste was mainly in the crust being more "flavored". Is this due to the 24 hour rise (usually I make it within 1-2 hours) or because of the low yeast? Who knows. I am going to make a full-yeast pizza and let it rise for 24 hours and taste-test it and see what's up.

**Comment by hendricius** [comment]
I hope I explained it a bit better in the recipe now. In winter times you would want to use a bit more yeast, in summer less yeast. It depends a lot on your dough's temperature :-)
