### ISSUE TITLE
height: 100% is breaking the app

### ISSUE THREAD

**Issue by bdougie** [hendricius/pizza-dough#64]
# Hi, I found an issue.

I was testing this out and found there is inconsistency with the vertical height and the page. I did not do anything but seeing the page at 100% is weird. 

## Chrome Canary
![Screen Shot 2020-08-04 at 4 20 16 PM](https://user-images.githubusercontent.com/5713670/89354917-eda54780-d66e-11ea-94ea-5b5e492ede43.png)

## Chrome 84
![Screen Shot 2020-08-04 at 4 20 20 PM](https://user-images.githubusercontent.com/5713670/89354900-e3834900-d66e-11ea-81d3-b65c7c021243.png)

## Firefox
![Screen Shot 2020-08-04 at 4 20 36 PM](https://user-images.githubusercontent.com/5713670/89354801-ac149c80-d66e-11ea-968f-f3e083e66002.png)

## Safari

![Screen Shot 2020-08-04 at 4 23 31 PM](https://user-images.githubusercontent.com/5713670/89354882-dcf4d180-d66e-11ea-8b53-e007d5cfb4a5.png)

# Potential solution
remove the height: 100%

**Comment by szepeviktor** [comment]
@hendricius fixed it: https://github.com/hendricius/pizza-dough/pull/65#issuecomment-1001579133
