### ISSUE TITLE
Add License? 

### ISSUE THREAD

**Issue by Guru107** [hendricius/pizza-dough#7]
This definitely needs a license. Else cloud providers will start giving out `Pizza Dough As A Service` 😅. 

On a serious note. Great Job. 👏

**Comment by Pizzacus** [comment]
If you add a license, remember **NOT** to add a "programming license", like MIT or GPL, because those are made for code, not content, actual content should use other licenses like Creative Common ^-^.

**Comment by Pizzacus** [comment]
\>not only did they use a programming license but they used the Unlicense

(-_-)
