### ISSUE TITLE
Food for thought

### ISSUE THREAD

**Issue by bdelmas** [hendricius/pizza-dough#8]
First thank you for this repo! 👍 

I wanted to share 2 resources to strive for the best pizza dough:
- [Jeff Varasano's Famous New York Pizza Recipe](http://www.varasanos.com/PizzaRecipe.htm)
- and [The Physics of baking good Pizza](https://arxiv.org/pdf/1806.08790.pdf)

I hope these will help to make the best dough!

**Comment by hendricius** [comment]
How about adding a pull request which adds another file including further resources?
