### ISSUE TITLE
Time calculator

### ISSUE THREAD

**Issue by thomasa88** [hendricius/pizza-dough#91]
It would be nice to have a time calculator, that follows your schedule, starting at the given time.

I'm not very good at Javascript frameworks, so I just threw together an example hack in jsfiddle:
https://jsfiddle.net/thomasa88/1sd7o2m6/54/

![image](https://user-images.githubusercontent.com/89997/147749810-b9a05e8a-8bed-42c4-b8ba-d4e3027c5829.png)

**Comment by hendricius** [comment]
That would be a nice idea indeed. The only problem I can see is that the time will always vary depending on the ambient temperature in your kitchen. I developed the version originally in summer, things were a bit faster then.

The best way for the recipe would be:
1) Mix dough
2) Knead a bit
3) Wait one hour
4) Stretch and fold once
5) Sleep
6) Stretch and fold after waking up
7) Dough is ready when it has increased by around 50% in size
8) Make pizza balls if want to make the pizza in ±3 hours, or, move dough to the fridge for up to a week.
9) If you refridgerate, take the dough out of fridge 3 hours before you want to make the pizza

Maybe a flowchart diagram would help? My process is a bit simpler now :-)

**Comment by hendricius** [comment]
I have simplified this in https://github.com/hendricius/pizza-dough/pull/97
